---
all:
  vars:
    ansible_user: admin  
    ansible_become_user: root
jenkins: 
  hosts:
    ec2-54-93-124-68.eu-central-1.compute.amazonaws.com
docker:
  hosts:
    ec2-54-93-124-68.eu-central-1.compute.amazonaws.com
grafana:
  hosts:
    ec2-3-79-99-247.eu-central-1.compute.amazonaws.com
prometheus:
  hosts:
    ec2-18-197-107-54.eu-central-1.compute.amazonaws.com